# Generated by Django 4.2.1 on 2023-05-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is description'),
            preserve_default=False,
        ),
    ]
