# Generated by Django 4.2.1 on 2023-05-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='item_description',
        ),
    ]
