# Generated by Django 4.2.1 on 2023-05-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
